name: Push To Master Workflow

on:
  push:
    branches:
      - master

jobs:
  get-version:
    name: Get Version
    runs-on: ubuntu-latest
    permissions:
      actions: write
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          fetch-depth: 0
      - name: Setup .NET
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: 8.0.x
      - name: Setup GitVersion
        uses: gittools/actions/gitversion/setup@v4.1.0
        with:
          versionSpec: '6.4.x'
      - name: Determine Version
        id: version_step
        uses: gittools/actions/gitversion/execute@v4.1.0
      - name: Push New Version Tag
        run: |
          gv=${{ steps.version_step.outputs.majorMinorPatch }} #gitversion result
          lt=$( git describe --tags --abbrev=0 ) # last tag version result
          if [[ $gv != $lt ]]; then
            git tag $gv
            git push origin --tags
          fi